import{a as b,S as P,i as a}from"./assets/vendor-BLPZKqeQ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const S="49857311-6635cfa9567008bd9332ca8ce",q="https://pixabay.com/api/";async function g(s,t=1){const r={key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};try{return(await b.get(q,{params:r})).data}catch(n){throw console.error(n),n}}const m=document.querySelector(".gallery"),h=document.querySelector(".loader");let B=new P(".gallery a");function p(s){const t=s.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p><span class="info-title"><strong>Likes</strong></span> ${r.likes}</p>
        <p><span class="info-title"><strong>Views</strong></span> ${r.views}</p>
        <p><span class="info-title"><strong>Comments</strong></span> ${r.comments}</p>
        <p><span class="info-title"><strong>Downloads</strong></span> ${r.downloads}</p>
      </div>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",t),B.refresh()}function $(){m.innerHTML=""}function y(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}const I=document.querySelector(".form"),f=document.querySelector(".load-more");let i=1,c="",u=0;const w=15;function v(){f.classList.remove("hidden")}function l(){f.classList.add("hidden")}I.addEventListener("submit",async s=>{if(s.preventDefault(),c=s.target.elements["search-text"].value.trim(),!c){a.warning({message:"Please enter a search term"});return}i=1,$(),l(),y();try{const t=await g(c,i);if(u=t.totalHits,t.hits.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again!"});return}p(t.hits),i*w>=u?(l(),a.info({message:"We're sorry, but you've reached the end of search results."})):v()}catch{a.error({message:"Something went wrong"})}finally{L(),s.target.reset()}});f.addEventListener("click",async()=>{i++,y(),l();try{const s=await g(c,i);p(s.hits);const t=document.querySelectorAll(".gallery-item");if(t.length>0){const n=t[0].querySelector("img");if(n){const{height:e}=n.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}i*w>=u?(a.info({message:"We're sorry, but you've reached the end of search results."}),l()):v()}catch{a.error({message:"Something went wrong while loading more images."})}finally{L()}});
//# sourceMappingURL=index.js.map
